title: Avinash Iyer
email: iyer@virginia.edu
description: >- # this means to ignore newlines until "baseurl:"
  First year mathematics PhD student at the University of Virginia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ai.avinash-iyer.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ai-bearing
markdown: kramdown
header_pages:
  - resources.md
  - honorsthesis.md
  #- expository_writings.md
  #- classnotes.md

# Build settings
theme: minima
plugins:
  - jekyll-feed
